<a href="https://colab.research.google.com/github/melvindeepesh-boop/Deep-Learning-Lab/blob/main/xor_dnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

In [6]:
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]], dtype="float32")

In [7]:
y = np.array([
    [0],
    [1],
    [1],
    [0]
], dtype="float32")


In [8]:
print("Input:")
print(X)

print("\nOutput:")
print(y)

Input:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]

Output:
[[0.]
 [1.]
 [1.]
 [0.]]


In [9]:
model = keras.Sequential([
    layers.Dense(8, activation="relu", input_shape=(2,)),
    layers.Dense(4, activation="relu"),
    layers.Dense(1, activation="sigmoid")
])

print("Model Created Successfully")

Model Created Successfully


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

print("Model Compiled Successfully")

Model Compiled Successfully


In [11]:
history = model.fit(
    X,
    y,
    epochs=500,
    verbose=1
)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.7500 - loss: 0.7172
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5000 - loss: 0.7164
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.7500 - loss: 0.7155
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.7500 - loss: 0.7146
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.7500 - loss: 0.7138
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.7500 - loss: 0.7130
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7500 - loss: 0.7121
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.7500 - loss: 0.7113
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7500 - loss: 0.7104
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7500 - loss: 0.7096
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7500 - loss: 0.7089
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7500 - loss

In [12]:
loss, accuracy = model.evaluate(X, y, verbose=0)

print("Loss:", loss)
print("Accuracy:", accuracy)

Loss: 0.4247764050960541
Accuracy: 1.0


In [13]:
predictions = model.predict(X)

print("Predicted Probabilities:")
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
Predicted Probabilities:
[[0.3929249 ]
 [0.68568933]
 [0.72344375]
 [0.3928259 ]]


In [14]:
print("Predicted Classes:")
print(predictions.round().astype(int))

Predicted Classes:
[[0]
 [1]
 [1]
 [0]]


In [15]:
print("Actual Output:")
print(y.astype(int))

Actual Output:
[[0]
 [1]
 [1]
 [0]]


In [16]:
print("Experiment Completed Successfully!")
print("The Deep Neural Network learned the XOR function correctly.")

Experiment Completed Successfully!
The Deep Neural Network learned the XOR function correctly.
